# vim:ft=yaml
#
# 2018/09
# Marcus Vinicius Ferreira               ferreira.mv[ at ]gmail.com
#


# Downloaded VDI file from
# https://cdn.amazonlinux.com/os-images/latest/virtualbox/
vdi: "~/Downloads/iso/amzn2-virtualbox-2.0.20180810-x86_64.xfs.gpt.vdi"

# Guest Additions from local installed Virtuabox
# path: MacOS installation
add: "/Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso"

# userdata and metadata for this vm
userdata: config/user-data.1.yml
metadata: config/meta-data.1.yml

# wip: temp name
machine_name: "amzn2-2018"

# wip: Local cloud-init boot iso
# TODO: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html
iso: "./amzn2/seed-data.iso"

