#cloud-config
# vim:syntax=yaml
#
# Ref:
#   https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html
#

local-hostname: amazonlinux.onprem

# network: defined by Virtualbox
#
#network-interfaces: |
#  auto eth0
#  iface eth0 inet static
#  address 192.168.1.10
#  network 192.168.1.0
#  netmask 255.255.255.0
#  broadcast 192.168.1.255
#  gateway 192.168.1.254

